### ISSUE TITLE
FRAME_SIZE_ERROR while sending it to multiple devices

### ISSUE THREAD

**Issue by sumeet559** [AndrewBarba/apns2#7]
while using notifications on multiple devices sometimes it throws

Error: Uncaught, unspecified "error" event. (FRAME_SIZE_ERROR)

Does anyone know about this. I am sure its from http2 module. Can't it be caught?

This error doesn't reproduce every time too.

**Comment by Black-Star** [comment]
Same error..

Below is the error
```
AssertionError: false == true
    at Connection._send (/home/ubuntu/message-sender/js/node_modules/http2/lib/protocol/connection.js:326:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
Error: Uncaught, unspecified "error" event. (FRAME_SIZE_ERROR)
    at Endpoint.emit (events.js:163:17)
    at Endpoint.onerror (_stream_readable.js:579:12)
    at emitOne (events.js:96:13)
    at Endpoint.emit (events.js:188:7)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by AndrewBarba** [comment]
Hey guys, I'm looking at switching to https://github.com/indutny/node-spdy and also keeping a close eye on the official https://github.com/nodejs/http2. Will update this issue as I make progress.

**Comment by AndrewBarba** [comment]
Switched http2 lib to node-spdy, closing
