### ISSUE TITLE
Could be a problem with topic ?  / defaultTopic ?

### ISSUE THREAD

**Issue by smhk** [AndrewBarba/apns2#85]
"TypeError: Cannot read properties of undefined (reading 'topic')"

```
apnsClient, send error undefined
undefined
TypeError: Cannot read properties of undefined (reading 'topic')
    at ApnsClient._send (/home/ubuntu/main/node_modules/apns2/dist/apns.js:51:52)
    at ApnsClient.send (/home/ubuntu/main/node_modules/apns2/dist/apns.js:35:21)
    at sendNotifs (/home/ubuntu/main/main.js:355:20)
    at /home/ubuntu/main/main.js:315:4
    at Layer.handle [as handle_request] (/home/ubuntu/main/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/main/node_modules/express/lib/router/route.js:149:13)
    at /home/ubuntu/main/node_modules/body-parser/lib/read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at invokeCallback (/home/ubuntu/main/node_modules/raw-body/index.js:238:16)
    at done (/home/ubuntu/main/node_modules/raw-body/index.js:227:7)
```

same production or sandbox

```
const apnsClient = new ApnsClient({
	team: `BGP36TQ2W7`,
	keyId: `PL62KVXW34`,
	signingKey: p8key,
	defaultTopic: `softwaremoderna.com.phonedemostaging`
})

```
I tried both **defaultTopic** and **topic** at the end there ?

Tears!

**Comment by AndrewBarba** [comment]
Interesting, looking into this. Are you using TypeScript or JavaScript? It seems like notification constructor is not working correctly, it should always have a default `options` property which is where we read topic from. The fact that is undefined is very suspect.

**Comment by smhk** [comment]
@AndrewBarba  thank you so much, am using JavaScript.  that is literally every line of code

I tried setting the topic "manually", things like

new Notification(aTokenData, { alert: 'apns yoyo', topic .. etc })

but I couldn't get it

more info ..

**Comment by smhk** [comment]
I have used (only) apns2 in the past and it always worked.  (Notice my long post here! https://stackoverflow.com/a/60550859/294884 ) I haven't done push for a yr or two and I can't access the previous client projects, so dunno.

I bring up exactly like this ..

![Screenshot 2024-07-10 at 2 47 22 PM](https://github.com/AndrewBarba/apns2/assets/3938526/011d3ee9-6092-4bb8-bbb9-b6d5eb4200f5)

(I deliberately made wrong the various other data items, to ensure that, was not the issue; ie I would incorrectly get "wrong key" etc from Apple ... all working great)

Here the current code for it sending, live on server now, (I also tried the pink alternates extensively),

![Screenshot 2024-07-10 at 2 50 25 PM](https://github.com/AndrewBarba/apns2/assets/3938526/b38e8249-1daa-4bbd-8f81-5f143a0836bd)

result right now when I try it ..

![Screenshot 2024-07-10 at 2 53 51 PM](https://github.com/AndrewBarba/apns2/assets/3938526/2ee737d5-89d2-4498-af64-41eede925faa)

hopefully just some dumb mistake on my part @AndrewBarba  !

thanks !!!!!

**Comment by AndrewBarba** [comment]
And you're using the latest version right? v11.7.0?

**Comment by smhk** [comment]
Yes, latest version checked!

I looked through the source https://github.com/AndrewBarba/apns2/blob/main/src/apns.ts but couldn't find any clues. Could it relate to the default for topic or defaultTopic?

Am more than happy to console.log anything that could help

I noticed there's an email on your git account so I sent along the actual runnable file, you never know

![Screenshot 2024-07-10 at 7 34 14 PM](https://github.com/AndrewBarba/apns2/assets/3938526/d47e4f6b-aa25-43aa-be9a-1699f3f85804)

**Comment by smhk** [comment]
Could a problem be caused by

`const { ApnsClient } = require('apns2')`

rather than

`import { ApnsClient } from 'apns2'`

The import form doesn't work in my project.

**Comment by smhk** [comment]
Cheers - damn, I've just realized the problem happens at THIS line of code

            new Notification(aTokenData, { alert: 'apns yoyo2' })



(it does not actually get to

    try {
        await apnsClient.send(nts)


!!

**Comment by AndrewBarba** [comment]
Yeah something is fishy passing in a buffer, can you try `new Notification(aTokenData.toString('hex'), { alert: 'apns yoyo2' })`

**Comment by smhk** [comment]
Finally!!

this minimal node file (with actual working tokens etc) works perfectly, just run:

￼


making minimal files that work is such a drag, lol




** ALSO !  I'm almost certain there is an unrelated problem:

* apnsClient.send( .. an array )

works perfectly

* apnsClient.send( one item )

i think it fails, specifically, it does something weird to the token and the token is incorrectly declared invalid.

**Comment by AndrewBarba** [comment]
I doubt the array version is actually sending the token. The array variant will resolve to an array of results, and if you log those results I bet you see that there was an error

**Comment by smhk** [comment]
OK that does NOT solve the "topic problem"

(it can be tested easily in my "perfect test file" in previous email!



Also, I tested that to solve the "one-off" problem, it does not solve the "one-off" problem .. demo ..

￼

**Comment by smhk** [comment]
indeed I think possibly it does not even get to that ...

the problem seems to happen here:

            new Notification(aTokenData, { alert: 'apns yoyo2' })

it crashes at that line of code ... it just can't populate a Notification possibly?

**Comment by smhk** [comment]
I even pushed it on explicitly like this, and the same!


￼

**Comment by smhk** [comment]
No luck with this one guys ?!

**Comment by AndrewBarba** [comment]
Did you trying calling toString(hex) on the buffer? You cannot pass in a buffer to the new Notification()
