### ISSUE TITLE
can you please help with this error?

### ISSUE THREAD

**Issue by raviten** [AndrewBarba/apns2#9]
AssertionError: false == true
    at Connection._send (/home/ubuntu/message-sender/js/node_modules/http2/lib/protocol/connection.js:326:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

**Comment by AndrewBarba** [comment]
Switched to http2 lib to node-spdy, closing this
